### PR TITLE
update for new tendon-robot

### PR DESCRIPTION
**Pull request by haraduka**

### CODE REVIEW

**Comment by cretaceous-creature** [comment]
GJ.
Do you have a link for the Kduino  IMU msg?

**Comment by haraduka** [comment]
https://github.com/jsk-ros-pkg/jsk-ros-pkg-unreleased/tree/master/jsk_rosserial_arduino/kduino

**Comment by cretaceous-creature** [comment]
That is a problem...
Inaba sensei want himself or new students to easily use this package....
Anyway we just write it in the readme. 
I guess I will merge after the mag problem is solved...

**Comment by haraduka** [comment]
I made new ros package jsk_imu_mini_msgs and remove the private package kduino.
So we do not need to use private packages now.
And I think the mag problem disappeared... I do know why...

**Comment by cretaceous-creature** [comment]
....that's is a good news, 
but I would rather hope it always happens than happens sometimes..
Let me merge this..

**Pull request merged**
